variables:
  CONTAINER_IMAGE: '927223451584.dkr.ecr.sa-east-1.amazonaws.com/escrutinio-paralelo:latest' 
  REGION: "sa-east-1"

image: b4ck3r/aws-cli:latest 

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - ./ci/build.sh

deploy:
  stage: deploy
  script:
    - ./ci/deploy.sh
  only:
    - setup-ci
