variables:
  CONTAINER_IMAGE: '927223451584.dkr.ecr.sa-east-1.amazonaws.com/escrutinio-paralelo:latest' 
  REGION: "sa-east-1"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

stages:
  - build
  - test  
  - deploy

build:
  stage: build
  image: docker:stable
  services:
    - docker:stable-dind
  before_script:
    - apk -uv add --no-cache groff bash jq less git py-pip
    - pip install --no-cache-dir awscli
  script:
    - ./ci/build.sh
  tags:
    - docker

test:
  stage: test
  image: tiangolo/docker-with-compose
  script:
    - make build
    - make test
  coverage: "/TOTAL.+ ([0-9]{1,3}%)/"
  artifacts:
    paths:
      - htmlcov
    expire_in: 1 days

deploy:
  stage: deploy
  image: b4ck3r/aws-cli:latest 
  script:
    - ./ci/deploy.sh
  only:
    - develop
  tags:
    - docker
