dist: xenial
language: python
python:
    - "3.7"

before_install:
    sudo apt install -y gdal-bin

services:
    - postgresql

pip:
    - pip install -r requirements.txt

before_script:
  - psql -c 'create database travis_ci;' -U postgres

script:
    - pytest
