dist: xenial
language: python
python:
    - "3.7"

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update -y
  - sudo apt-get install -y gdal-bin

services:
    - postgresql

pip:
    - pip install -r requirements.txt

before_script:
  - psql -c 'create database travis_ci;' -U postgres

script:
    - pytest

notifications:
  slack: opendatacba:Pweez1BZ9RgtrReYzopBPMUh