dist: xenial
language: python
python:
    - "3.7"

services:
    - postgresql

pip:
    - pip install -r requirements.txt

before_script:
  - psql -c 'create database travis_ci;' -U postgres

script:
    - pytest
