version: "3"

services:
  db:
    image: postgres:11
    container_name: escrutinio-social-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=db_name
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data
    shm_size: '2gb'
  app:
    container_name: escrutinio-social-app
    build: .
    command: ./runner.sh
    environment:
      #- DATABASE_URL=postgres://postgres@db/postgres
      - DB_NAME=db_name
      - DB_USER=postgres
      - DB_PASS=changeme
      - DB_HOST=db
    volumes:
      - .:/src
    ports:
      - "8000:8000"
      - "8080:8080"
    depends_on:
      - db

volumes:
  data:
