version: "3"

services:
  db:
    image: postgres:11
    container_name: escrutinio-social-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=db_name
    ports:
      - "5433:5432"
    volumes:
      - data:/var/lib/postgresql/data

  app:
    container_name: escrutinio-social-app
    build: .
    command: bash -c "python manage.py migrate && python manage.py createcachetable && gunicorn escrutinio_social.wsgi"
    environment:
      - DB_NAME=db_name
      - DB_USER=postgres
      - DB_PASS=changeme
      - DB_HOST=db
      - GUNICORN_WORKERS=2
    ports:
      - "8000:8000"
    depends_on:
      - db

  scheduler:
    container_name: escrutinio-social-scheduler
    build: .
    command: python3 manage.py scheduler
    environment:
      - DB_NAME=db_name
      - DB_USER=postgres
      - DB_PASS=changeme
      - DB_HOST=db
    depends_on:
      - app

  importer:
    container_name: escrutinio-social-importer
    build: .
    command: python3 manage.py importar_csv
    environment:
      - DB_NAME=db_name
      - DB_USER=postgres
      - DB_PASS=changeme
      - DB_HOST=db
    depends_on:
      - app

volumes:
  data:
